/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    applications: Application;
    'menu-items': MenuItem;
    roles: Role;
    permissions: Permission;
    'audit-logs': AuditLog;
    notifications: Notification;
    'api-keys': ApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'portal-settings': PortalSetting;
  };
  globalsSelect: {
    'portal-settings': PortalSettingsSelect<false> | PortalSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Full name from Keycloak
   */
  name?: string | null;
  /**
   * Keycloak user ID (sub claim) for shadow user sync
   */
  keycloak_sub?: string | null;
  /**
   * User roles for RBAC
   */
  roles?: (number | Role)[] | null;
  updatedAt: string;
  createdAt: string;
  /**
   * Email from Keycloak
   */
  email?: string | null;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Role-Based Access Control (RBAC) roles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * Role display name (e.g., Super Admin)
   */
  name: string;
  /**
   * Role identifier (e.g., super_admin)
   */
  slug: string;
  /**
   * Role description and responsibilities
   */
  description?: string | null;
  /**
   * System roles cannot be deleted
   */
  type: 'system' | 'custom';
  /**
   * Permissions granted to this role
   */
  permissions?: (number | Permission)[] | null;
  /**
   * Inherit permissions from other roles
   */
  inheritsFrom?: (number | Role)[] | null;
  /**
   * Priority level (higher = more permissions)
   */
  priority?: number | null;
  /**
   * Active/inactive role
   */
  active?: boolean | null;
  /**
   * Number of users with this role (computed)
   */
  usersCount?: number | null;
  /**
   * Additional metadata
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Granular permissions (resource.action)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  /**
   * Permission name (e.g., users:create)
   */
  name: string;
  /**
   * Human-readable description
   */
  description?: string | null;
  /**
   * Resource type
   */
  resource:
    | 'users'
    | 'roles'
    | 'permissions'
    | 'applications'
    | 'menu_items'
    | 'audit_logs'
    | 'notifications'
    | 'api_keys'
    | 'portal_settings'
    | '*';
  /**
   * Allowed actions
   */
  action: ('create' | 'read' | 'update' | 'delete' | 'export' | 'import' | '*')[];
  /**
   * Scope of permission (e.g., own = only own records)
   */
  scope: 'global' | 'own' | 'team' | 'org';
  /**
   * Additional conditions (JSON format)
   */
  conditions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Permission category for organization
   */
  category?: ('portal' | 'users' | 'security' | 'compliance' | 'business') | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage external applications registered in the portal
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  /**
   * Display name of the application
   */
  name: string;
  /**
   * Unique identifier (URL-friendly)
   */
  slug: string;
  /**
   * Brief description of the application
   */
  description?: string | null;
  /**
   * Full URL of the application (will be loaded in iframe)
   */
  url: string;
  /**
   * Icon name (Lucide icon)
   */
  icon?: string | null;
  /**
   * Current status of the application
   */
  status: 'active' | 'inactive' | 'maintenance';
  /**
   * Open application in new tab instead of iframe
   */
  openInNewTab?: boolean | null;
  /**
   * Iframe rendering settings
   */
  iframeSettings?: {
    /**
     * Iframe sandbox permissions
     */
    sandbox?: ('allow-scripts' | 'allow-forms' | 'allow-same-origin' | 'allow-popups' | 'allow-modals')[] | null;
    allowFullscreen?: boolean | null;
  };
  /**
   * Health check configuration
   */
  healthCheck?: {
    enabled?: boolean | null;
    endpoint?: string | null;
    intervalSeconds?: number | null;
  };
  /**
   * Additional metadata (JSON format)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage portal sidebar menu structure
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  /**
   * Menu item label (supports i18n)
   */
  label: string;
  /**
   * Type of menu item
   */
  type: 'application' | 'external' | 'divider' | 'group';
  /**
   * Link to registered application
   */
  application?: (number | null) | Application;
  /**
   * External URL
   */
  externalUrl?: string | null;
  /**
   * Icon name (Lucide icon)
   */
  icon?: string | null;
  /**
   * Parent menu item (for nested menus)
   */
  parent?: (number | null) | MenuItem;
  /**
   * Display order (lower numbers appear first)
   */
  order: number;
  /**
   * Show/hide menu item
   */
  visible?: boolean | null;
  /**
   * Badge configuration (notifications, counts)
   */
  badge?: {
    enabled?: boolean | null;
    type?: ('static' | 'api') | null;
    /**
     * Static badge text
     */
    text?: string | null;
    /**
     * API endpoint to fetch badge value
     */
    apiEndpoint?: string | null;
    variant?: ('default' | 'primary' | 'success' | 'warning' | 'error') | null;
  };
  /**
   * Roles required to see this menu item (RBAC)
   */
  requiredRoles?:
    | {
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable audit logs for compliance (LGPD, BACEN)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  /**
   * Type of action performed
   */
  action:
    | 'create'
    | 'read'
    | 'update'
    | 'delete'
    | 'login'
    | 'logout'
    | 'failed_login'
    | 'password_change'
    | 'export_data'
    | 'import_data';
  /**
   * User who performed the action
   */
  user: number | User;
  /**
   * Resource affected (e.g., users, applications)
   */
  resource: string;
  /**
   * ID of the resource
   */
  resourceId?: string | null;
  /**
   * Additional details (changes, metadata)
   */
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * IP address of the client
   */
  ipAddress?: string | null;
  /**
   * Browser/client user agent
   */
  userAgent?: string | null;
  status: 'success' | 'failed' | 'error';
  /**
   * Error message if status is failed/error
   */
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-app notifications for users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * Notification title
   */
  title: string;
  /**
   * Notification message
   */
  message: string;
  /**
   * Notification type (affects icon and color)
   */
  type: 'info' | 'success' | 'warning' | 'error';
  /**
   * User who will receive the notification
   */
  recipient: number | User;
  /**
   * Has the user read this notification?
   */
  read?: boolean | null;
  /**
   * Timestamp when notification was read
   */
  readAt?: string | null;
  /**
   * Optional action (link, button)
   */
  action?: {
    label?: string | null;
    url?: string | null;
    openInNewTab?: boolean | null;
  };
  /**
   * Additional metadata (JSON format)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Auto-delete notification after this date
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys for external applications integration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  /**
   * Friendly name for this API key
   */
  name: string;
  /**
   * API key (auto-generated, read-only)
   */
  key: string;
  /**
   * API secret (hashed, shown only once on creation)
   */
  secret?: string | null;
  /**
   * Application this key belongs to
   */
  application?: (number | null) | Application;
  /**
   * User who created this key
   */
  owner: number | User;
  /**
   * API key status
   */
  status: 'active' | 'inactive' | 'revoked' | 'expired';
  /**
   * Permissions granted to this API key
   */
  permissions?: (number | Permission)[] | null;
  /**
   * Rate limiting configuration
   */
  rateLimit?: {
    enabled?: boolean | null;
    requestsPerMinute?: number | null;
    requestsPerHour?: number | null;
  };
  /**
   * IP addresses allowed to use this key
   */
  ipWhitelist?:
    | {
        ip: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Expiration date (optional)
   */
  expiresAt?: string | null;
  /**
   * Last time this key was used
   */
  lastUsedAt?: string | null;
  /**
   * Number of times this key has been used
   */
  usageCount?: number | null;
  /**
   * Additional metadata
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'permissions';
        value: number | Permission;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  keycloak_sub?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  url?: T;
  icon?: T;
  status?: T;
  openInNewTab?: T;
  iframeSettings?:
    | T
    | {
        sandbox?: T;
        allowFullscreen?: T;
      };
  healthCheck?:
    | T
    | {
        enabled?: T;
        endpoint?: T;
        intervalSeconds?: T;
      };
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  application?: T;
  externalUrl?: T;
  icon?: T;
  parent?: T;
  order?: T;
  visible?: T;
  badge?:
    | T
    | {
        enabled?: T;
        type?: T;
        text?: T;
        apiEndpoint?: T;
        variant?: T;
      };
  requiredRoles?:
    | T
    | {
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  type?: T;
  permissions?: T;
  inheritsFrom?: T;
  priority?: T;
  active?: T;
  usersCount?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  resource?: T;
  action?: T;
  scope?: T;
  conditions?: T;
  category?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  user?: T;
  resource?: T;
  resourceId?: T;
  details?: T;
  ipAddress?: T;
  userAgent?: T;
  status?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  type?: T;
  recipient?: T;
  read?: T;
  readAt?: T;
  action?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
      };
  metadata?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  secret?: T;
  application?: T;
  owner?: T;
  status?: T;
  permissions?: T;
  rateLimit?:
    | T
    | {
        enabled?: T;
        requestsPerMinute?: T;
        requestsPerHour?: T;
      };
  ipWhitelist?:
    | T
    | {
        ip?: T;
        id?: T;
      };
  expiresAt?: T;
  lastUsedAt?: T;
  usageCount?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global portal configuration (branding, i18n, themes)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-settings".
 */
export interface PortalSetting {
  id: number;
  /**
   * Portal display name
   */
  portalName: string;
  /**
   * Portal logo (shown in header)
   */
  logo?: (number | null) | Media;
  /**
   * Browser favicon
   */
  favicon?: (number | null) | Media;
  /**
   * Primary brand color (hex)
   */
  primaryColor?: string | null;
  /**
   * Secondary brand color (hex)
   */
  secondaryColor?: string | null;
  /**
   * Default portal language
   */
  defaultLanguage: 'pt-BR' | 'en-US' | 'es-ES';
  /**
   * Enabled languages for users to select
   */
  enabledLanguages: ('pt-BR' | 'en-US' | 'es-ES')[];
  dateFormat?: ('DD/MM/YYYY' | 'MM/DD/YYYY' | 'YYYY-MM-DD') | null;
  timeFormat?: ('24h' | '12h') | null;
  /**
   * Default color theme
   */
  defaultTheme?: ('light' | 'dark' | 'system') | null;
  /**
   * Allow users to override theme
   */
  allowUserThemeSelection?: boolean | null;
  /**
   * Session timeout in seconds (default: 1 hour)
   */
  sessionTimeout?: number | null;
  /**
   * Max failed login attempts before lockout
   */
  maxLoginAttempts?: number | null;
  passwordPolicy?: {
    minLength?: number | null;
    requireUppercase?: boolean | null;
    requireLowercase?: boolean | null;
    requireNumbers?: boolean | null;
    requireSpecialChars?: boolean | null;
  };
  /**
   * Enable audit logging for compliance
   */
  enableAuditLogs?: boolean | null;
  /**
   * Enable in-app notifications
   */
  enableNotifications?: boolean | null;
  /**
   * Enable maintenance mode (blocks user access)
   */
  maintenanceMode?: boolean | null;
  /**
   * Message shown during maintenance
   */
  maintenanceMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-settings_select".
 */
export interface PortalSettingsSelect<T extends boolean = true> {
  portalName?: T;
  logo?: T;
  favicon?: T;
  primaryColor?: T;
  secondaryColor?: T;
  defaultLanguage?: T;
  enabledLanguages?: T;
  dateFormat?: T;
  timeFormat?: T;
  defaultTheme?: T;
  allowUserThemeSelection?: T;
  sessionTimeout?: T;
  maxLoginAttempts?: T;
  passwordPolicy?:
    | T
    | {
        minLength?: T;
        requireUppercase?: T;
        requireLowercase?: T;
        requireNumbers?: T;
        requireSpecialChars?: T;
      };
  enableAuditLogs?: T;
  enableNotifications?: T;
  maintenanceMode?: T;
  maintenanceMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}